### ISSUE TITLE
unknown sql type: point

### ISSUE THREAD

**Issue by insanebaba** [quek/arysn#4]
Hi There,

I'm using postgis in my postgres database.
I am unable to create postgis __Point__ data type variables for my table.

Is there a way around?

**Comment by quek** [comment]
Thanks for the Issue.
I'm trying to implement it, but it's going to take some time.

**Comment by quek** [comment]
I released version 0.1.8, please give it a try.
`gis` featuers is required.

Cargo.toml

``` toml
[dependencies]
arysn = { version = "0.1.8", features = ["gis"] }
```
